"""initial schema

Revision ID: 73ccc99c279f
Revises: 
Create Date: 2026-08-04 15:18:47.013631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '73ccc99c279f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('system_name', sa.String(length=200), nullable=True),
    sa.Column('system_type', sa.Enum('county', 'municipal', 'academic', 'private', 'special', name='systemtype'), nullable=False),
    sa.Column('catalog_system', sa.String(length=50), nullable=True),
    sa.Column('hours_json', sa.JSON(), nullable=True),
    sa.Column('is_24_hour', sa.Boolean(), nullable=False),
    sa.Column('closing_time', sa.Time(), nullable=True),
    sa.Column('access_level', sa.Enum('open_to_all', 'card_required', 'day_pass', 'students_only', 'members_only', 'appointment_only', name='accesslevel'), nullable=False),
    sa.Column('wifi_policy', sa.Enum('free', 'card_only', 'day_pass', 'guest_pass_at_desk', 'not_available', name='wifipolicy'), nullable=False),
    sa.Column('membership_required_for', sa.JSON(), nullable=True),
    sa.Column('access_notes', sa.Text(), nullable=True),
    sa.Column('walk_in_policy', sa.Enum('anytime', 'sign_in_at_desk', 'card_swipe', name='walkinpolicy'), nullable=False),
    sa.Column('outlet_density_score', sa.Integer(), nullable=True),
    sa.Column('seating_time_limit_min', sa.Integer(), nullable=True),
    sa.Column('has_long_term_seating', sa.Boolean(), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=True),
    sa.Column('has_quiet_zone', sa.Boolean(), nullable=False),
    sa.Column('has_outdoor_seating', sa.Boolean(), nullable=False),
    sa.Column('has_charging_stations', sa.Boolean(), nullable=False),
    sa.Column('has_free_water', sa.Boolean(), nullable=False),
    sa.Column('natural_light', sa.Boolean(), nullable=False),
    sa.Column('noise_policy', sa.Enum('strict_silence', 'quiet_talk', 'low_conversation', 'mixed', name='noisepolicy'), nullable=True),
    sa.Column('work_zones', sa.JSON(), nullable=True),
    sa.Column('recommended_for', sa.JSON(), nullable=True),
    sa.Column('parking_type', sa.Enum('free_lot', 'metered', 'paid_lot', 'validation', 'permit_only', 'street_only', 'none', name='parkingtype'), nullable=True),
    sa.Column('parking_notes', sa.Text(), nullable=True),
    sa.Column('has_bike_parking', sa.Boolean(), nullable=False),
    sa.Column('has_study_rooms', sa.Boolean(), nullable=False),
    sa.Column('has_public_computers', sa.Boolean(), nullable=False),
    sa.Column('has_printing', sa.Boolean(), nullable=False),
    sa.Column('has_outlets', sa.Boolean(), nullable=False),
    sa.Column('has_free_wifi', sa.Boolean(), nullable=False),
    sa.Column('is_wheelchair_accessible', sa.Boolean(), nullable=False),
    sa.Column('programs', sa.JSON(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('data_freshness_score', sa.Float(), nullable=True),
    sa.Column('scrape_source', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_libraries_city'), 'libraries', ['city'], unique=False)
    op.create_index(op.f('ix_libraries_name'), 'libraries', ['name'], unique=False)
    op.create_index(op.f('ix_libraries_slug'), 'libraries', ['slug'], unique=True)
    op.create_index(op.f('ix_libraries_zip_code'), 'libraries', ['zip_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('disclaimers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=300), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating_overall', sa.Integer(), nullable=False),
    sa.Column('rating_noise', sa.Integer(), nullable=True),
    sa.Column('rating_outlets', sa.Integer(), nullable=True),
    sa.Column('rating_seating', sa.Integer(), nullable=True),
    sa.Column('rating_staff', sa.Integer(), nullable=True),
    sa.Column('crowdedness', sa.String(length=20), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('speed_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('download_mbps', sa.Float(), nullable=False),
    sa.Column('upload_mbps', sa.Float(), nullable=False),
    sa.Column('ping_ms', sa.Float(), nullable=False),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speed_tests_created_at'), 'speed_tests', ['created_at'], unique=False)
    op.create_index(op.f('ix_speed_tests_library_id'), 'speed_tests', ['library_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_speed_tests_library_id'), table_name='speed_tests')
    op.drop_index(op.f('ix_speed_tests_created_at'), table_name='speed_tests')
    op.drop_table('speed_tests')
    op.drop_table('reviews')
    op.drop_table('disclaimers')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_libraries_zip_code'), table_name='libraries')
    op.drop_index(op.f('ix_libraries_slug'), table_name='libraries')
    op.drop_index(op.f('ix_libraries_name'), table_name='libraries')
    op.drop_index(op.f('ix_libraries_city'), table_name='libraries')
    op.drop_table('libraries')
    # ### end Alembic commands ###
